#!/bin/bash
##############################################################################
# LE1_VIS_MetadataCollector
# Script for the generation of Metadata (XML) files from info (XML) files,
# for the VIS data
#-----------------------------------------------------------------------------
# Usage:  LE1_VIS_MetadataCollector {cfgFile}
##############################################################################

# Set I/O directories and files
baseScriptName=${BASH_SOURCE##*/}

usage() {
    echo "Usage: $baseScriptName {cfgFile}"
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

cfgFile=$1
workDir=$(dirname $cfgFile)

cd ${workDir}

binPath=/qlabin
log=${workDir}/log/${baseScriptName}.log

# Run the processor
python ${binPath}/le1_vis.py --meta --input_path ${workDir}/ 1>${log} 2>&1
