#!/bin/bash
##############################################################################
# QLA_VIS
# Driver script for EUCLID QLA VIS Processor (python)
#-----------------------------------------------------------------------------
# Usage:  QLA_VIS {cfgFile}
##############################################################################

# Set I/O directories and files

usage() {
    echo "Usage: QLA_VIS  {cfgFile}"
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

cfgFile=$1
workDir=$(dirname $cfgFile)

cd ${workDir}

binPath=/qlabin
inPath=${workDir}/in
outPath=${workDir}/out

in=${inPath}/*.fits
id=$(basename $in .fits)
	 
idres=$(echo $id|sed -e 's#VIS_IMG#VIS_RES#g')
idrep=$(echo $id|sed -e 's#VIS_IMG#VIS_REP#g')
idlog=$(echo $id|sed -e 's#VIS_IMG#VIS_LOG#g')
	 
exe=driver.py
results=${outPath}/${idres}.json
report=${outPath}/${idrep}.json
log=${outPath}/${idlog}.log

# Run the processor

cd ${workDir}
python ${binPath}/${exe} -i ${inPath} -o ${report} -r ${results} -v 1>${log} 2>&1

# Compress results (can be large)

gzip ${results}
